### ISSUE TITLE
Determine correct creation date & de-dupe rights statement

### ISSUE THREAD

**Issue by sterkenburgsara** [HeardLibrary/exhibitions#20]
There are currently two `<date>` elements with the attribute "creation." Only one creation date is allowed. A publication or revision date would be acceptable, but there cannot be two separate dates of creation on one artifact. ([See here](https://github.com/HeardLibrary/exhibitions/blob/24e8afd7d516289b339c9596671d80b340335ab8/Metadata/Crime-in-the-Archives/Crime%20of%20the%20Century/MS0412-C-Lindbergh-Spirit_Autograph.xml#L24-31))

There are also two `<rights>` elements shown. I am assuming one refers to the autograph portion of the  item, and one to the photograph. These can be included in separate `<text>` subelements under the same `<rights>` element, but do not duplicate rights. Are we considering copyright separately for the two portions? ([See here](https://github.com/HeardLibrary/exhibitions/blob/24e8afd7d516289b339c9596671d80b340335ab8/Metadata/Crime-in-the-Archives/Crime%20of%20the%20Century/MS0412-C-Lindbergh-Spirit_Autograph.xml#L43-57))

**Comment by celiaswalker** [comment]
I am not sure how to remove the extra text here.  I am considering rights separately for each item.

**Comment by celiaswalker** [comment]
I added Lindbergh as the agent of the autograph
