### ISSUE TITLE
Edit: no tracing unauthorized agents

### ISSUE THREAD

**Issue by sterkenburgsara** [HeardLibrary/exhibitions#21]
The file [MS0412-C-Lindbergh-Spirit_Autograph.xml](https://github.com/HeardLibrary/exhibitions/blob/24e8afd7d516289b339c9596671d80b340335ab8/Metadata/Crime-in-the-Archives/Crime%20of%20the%20Century/MS0412-C-Lindbergh-Spirit_Autograph.xml) has an `<agent>` element with "unknown" as its contents, and with dates listed. We do not authorize/trace unknown agents (See Q1 [in the FAQ](https://github.com/HeardLibrary/exhibitions/wiki/FAQs)). Side question: we know the dates for an unknown agent? Maybe I am missing something. 

Referring [these lines in the XML](https://github.com/HeardLibrary/exhibitions/blob/24e8afd7d516289b339c9596671d80b340335ab8/Metadata/Crime-in-the-Archives/Crime%20of%20the%20Century/MS0412-C-Lindbergh-Spirit_Autograph.xml#L15-20).

**Comment by celiaswalker** [comment]
This is two items framed as one, so the first field is for the agent of the photograph taken for a newspaper article and the second agent is for the autograph.
