### ISSUE TITLE
Issue with length of description

### ISSUE THREAD

**Issue by celiaswalker** [HeardLibrary/exhibitions#27]
[Clip 2](https://github.com/HeardLibrary/exhibitions/blob/075de3422e677571d14ae6e34433be9c9e6e7644/Metadata/Photography/AV-Descriptions.md#clip-2--unknown-photographer-vivian-maier) | Unknown Photographer Vivian Maier is too long--needs to be cut to 500 characters.

**Comment by sterkenburgsara** [comment]
Still at 529 (make sure when you look at the "word count" you check characters _with spaces_: blank spaces count toward limits).
