### ISSUE TITLE
Add specificity to RefID

### ISSUE THREAD

**Issue by sterkenburgsara** [HeardLibrary/exhibitions#43]
There are currently two XML files for the work entitled 'Histoire Naturelle, Générale et Particulière', which according to the Acorn record, was published in 127 volumes between 1799-1808. Which volume are you using in the exhibit? Do both records reference the same one?

And is 1878 the true publication date? This record looks old/outdated so I trust you more than the record, but could you double check since it goes against the cataloging? [See file in question here](https://github.com/HeardLibrary/exhibitions/blob/d0c2fa79b233b012dd3b4a05cf735df668c09ef9/Metadata/1941/Histoire_Naturelle-1873.xml#L28).

**Comment by sterkenburgsara** [comment]
Could you review this issue? Thanks!

**Comment by celiaswalker** [comment]
extra file deleted; volume added and publication date changed.
