### ISSUE TITLE
Can you give me a little more context?

### ISSUE THREAD

**Issue by celiaswalker** [HeardLibrary/exhibitions#48]
Please expand the context for [this description](https://github.com/HeardLibrary/exhibitions/blob/f647a7c58a130a63405ac2e1b18308a64614903c/Metadata/Photography/MS0774-Amputee_Miner-1968.xml#L24).

**Comment by CliffordAnderson** [comment]
@celiaswalker Looks like you've already improved the description so I'm closing rather than assigning this issue to anyone. If I'm wrong about that, please reopen. Thanks!
