### ISSUE TITLE
add clarification to description

### ISSUE THREAD

**Issue by celiaswalker** [HeardLibrary/exhibitions#60]
Would you look at the adds I made on the description for the [Randolph Coyle](https://github.com/HeardLibrary/exhibitions/blob/07e7f0f55fd7933cb717e3300ffa0cdcce844bf4/Metadata/Visualizing-Data/Maps/MS0274-DV-McGaw_Map_64.xml#L23)  map and make sure you like them? Also, the last two sentences are a bit vague--could you clarify if the map is poorly drawn?

**Comment by langsdlc** [comment]
I really have nothing to clarify with.  This is not something I have extra information on.  Just going by my own visual comparison.
