### ISSUE TITLE
clarify description

### ISSUE THREAD

**Issue by celiaswalker** [HeardLibrary/exhibitions#61]
Would you look at the changes I made to the description of [Low's Map of Tennessee](https://github.com/HeardLibrary/exhibitions/blob/1d87b4a375f48006c638380b1f95868d1dbad334/Metadata/Visualizing-Data/Maps/MS0274-DV-McGaw_Map_25-1810.xml#L23) and make sure you agree with them? Also, please clarify the last two sentences describing how the mapmaker was off.

**Comment by langsdlc** [comment]
The description works.  Although, where did this information come from?
