### ISSUE TITLE
Add missing RefID and Agent(s)

### ISSUE THREAD

**Issue by sterkenburgsara** [HeardLibrary/exhibitions#62]
The XML doc "More_of_the_Shadow-C-Records-1979" in the _Making Money from Murder_ case is missing a refid to tell me where it came from in Special Collections. Please add. (Doesn't appear to be cataloged / I couldn't find it in Acorn - so likely an archival box #). See line in question [here](https://github.com/HeardLibrary/exhibitions/blob/24bad8387fa8e8bf906e36b79e0a2d022ac6a6c8/Metadata/Crime-in-the-Archives/Making%20Money%20from%20Murder/More_of_the_Shadow-C-Records-1979.xml#L28).

Also missing a publishing agent. All contributing agent(s) to an item must be traced. Was there a producer? If so, add them too. [See here](https://github.com/HeardLibrary/exhibitions/blob/24bad8387fa8e8bf906e36b79e0a2d022ac6a6c8/Metadata/Crime-in-the-Archives/Making%20Money%20from%20Murder/More_of_the_Shadow-C-Records-1979.xml#L13) for line in question.

**Comment by celiaswalker** [comment]
Kathy does not want to accession this item and asked me to leave that field blank. I have added publisher info,
