### ISSUE TITLE
Missing Date and Title elements

### ISSUE THREAD

**Issue by sterkenburgsara** [HeardLibrary/exhibitions#69]
The XML file for the Wire Recording is missing the agent, date, and title elements. 

Based on your description and other fields, it looks like the agent cannot be identified. This is fine. But the other two fields are required. Please fill in date (it's okay to use an approximate or estimated date range) - [see here](https://github.com/HeardLibrary/exhibitions/blob/9d24ac9e8609da991ad19a602322d19a80027244/Metadata/Satellite-Music/20150417SG049.xml#L8-11), and the title - [see here](https://github.com/HeardLibrary/exhibitions/blob/9d24ac9e8609da991ad19a602322d19a80027244/Metadata/Satellite-Music/20150417SG049.xml#L33). Thanks!

**Comment by smanus** [comment]
This was the item that we talked about a couple of months ago. It is in an unlabeled box, so no title is discernible. At that time, you said to describe the item in hand and to leave the elements blank that were unknown. I can put in a date range, but there is no title.

Sara

Sara J. Beutter Manus
Music Librarian for Education and Outreach
Anne Potter Wilson Music Library
Vanderbilt University
2400 Blakemore Avenue / Nashville, TN / 37212
(615) 322-8686

**Comment by sterkenburgsara** [comment]
Thanks for your response Sara.

My apologies. I did say that....(oops) but I shouldn't have spoken so definitively without realizing exactly which fields you meant. In general, it's completely okay that the item doesn't have its own given title. But for those situations, we have to create our own made up title and put it in square brackets (indicating a devised title). I can do that for you, but it crosses the line of cataloger into curatorial territory in my opinion, so I would feel more comfortable with you or Jake deciding. An exact date also isn't something we can usually expect to know. But at a minimum we have to include "unknown" - although literally anything is better than unknown: even a super wide range of dates (e.g. 1900-1960?; 20th century), etc. Sorry to get back with you pretty late on this one. If you don't want to deal with the XML, I can enter it for you. Just need a date entry and title entry of some kind that works for you - you can send it via email if that's easier. Thanks,

-Sara

**Comment by smanus** [comment]
Hi Sara,

No, it’s not a problem at all. I will make the changes. I thought I had asked about using square brackets, but maybe not.

Sara

Sara J. Beutter Manus
Music Librarian for Education and Outreach
Anne Potter Wilson Music Library
Vanderbilt University
2400 Blakemore Avenue / Nashville, TN / 37212
(615) 322-8686

**Comment by sterkenburgsara** [comment]
Great, thanks!

**Comment by sterkenburgsara** [comment]
Just a reminder to make these changes when you get the chance. Thanks!
