### ISSUE TITLE
Missing XML file for image: "Correspondence_of_Flannery-CR_Stephens-1986.jpg"

### ISSUE THREAD

**Issue by sterkenburgsara** [HeardLibrary/exhibitions#88]
In your LED selections folder there is an image entitled "Correspondence_of_Flannery-CR_Stephens-1986.jpg" but this image (a book jacket) has no corresponding XML record. 

This one should be pretty straightforward if you look it up in the Acorn catalog - many fields will already have been determined for you. Thanks!

**Comment by suellenstringer-hye** [comment]
Isn’t this the XML?

https://github.com/HeardLibrary/exhibitions/blob/master/Metadata/Visualizing-Data/Flannery-O-Connor/Correspondence_of_Flannery-CR_Stephens-1986.jpg

**Comment by sterkenburgsara** [comment]
No, that's a copy of the .jpg image.

**Comment by suellenstringer-hye** [comment]
Actually that was an xml file, it was just named wrong. I fixed it.

**Comment by sterkenburgsara** [comment]
Great -thanks for fixing.
