### ISSUE TITLE
Missing image for XML file: "graphgist.xml"

### ISSUE THREAD

**Issue by sterkenburgsara** [HeardLibrary/exhibitions#89]
Reverse problem for this one - I see an XML file (refers me to an html page on the gist.neo4j.com website), but no image or series of images to correspond with the record in your image folders. Do you have screenshots or something you can take of this page? 

Let me know if I'm just missing them (sorry if that's the case!).

If you plan to use any screenshots from this site in the interactive touchscreens, then could you email the screenshots to Henry and ask him to size them for FireSign? He will know what you mean. Thanks!

**Comment by suellenstringer-hye** [comment]
Aren’t we going to have the ability to directly connect to the webpage from the interactives. We’re kind of waiting to see what the designer wants to do with the image for the backdrop so we could use the same image. I think I have one in the LED selection as a placeholder. Should I point to that in the meantime?

**Comment by sterkenburgsara** [comment]
Ah, yes - we are. That's true. I'm not sure how to handle all of that exactly with XML and VRA, which is usually intended for objects and static images. For now, yes - let's use the LED selection as a placeholder. Could you add the image filename of that one in to the image portion of that record and rename the XML file so that they match? Thanks
