### ISSUE TITLE
Review date and agent elements

### ISSUE THREAD

**Issue by sterkenburgsara** [HeardLibrary/exhibitions#97]
Is there any way you can guess a range of dates for the chronometer? 

Right now you have "unknown" listed ([see here](https://github.com/HeardLibrary/exhibitions/blob/272ae7925832997e29ddfee4c7e3a8795800a89f/Metadata/Visualizing-Data/Astronomy/20150417SG007-008.xml#L15-16)), but an approximate date range is much better than this if you can comfortably suggest one (e.g. 1800-1900; 1820-1875, etc.).

Also, what is "Werke G.M.B.H."? It's listed as the agent ([see here](https://github.com/HeardLibrary/exhibitions/blob/272ae7925832997e29ddfee4c7e3a8795800a89f/Metadata/Visualizing-Data/Astronomy/20150417SG007-008.xml#L10)), but without a controlled vocabulary. I'm assuming it's a German company - possibly now defunct - but do you know what the G.M.B.H. stands for? What is their role in creating this artifact? I am hoping to add a few more details for this agent since we can't trace them. Thanks!

**Comment by graytl** [comment]
Hi Sara,

GmbH appears to be German for limited liability company (LLC): http://en.wikipedia.org/wiki/Gesellschaft_mit_beschr%C3%A4nkter_Haftung.

I’ll check the chronometer for any additional information.

Teresa

**Comment by graytl** [comment]
There’s nothing on the clock face except the name.  Apparently, this particular chronometer was made between 1905 and 1938 when the company was renamed Wempe: http://www.chronometerwerke-maritim.de/en/the_chronometerwerke/the_chronometerwerke.htm.

Teresa

**Comment by sterkenburgsara** [comment]
Excellent on the date! Would you mind changing the "unknowns" to that date range (1905 and 1938)? And on the agent - okay, if we can't find their name in the LCNAF database, what you have should be fine. Thanks for checking.

**Comment by graytl** [comment]
Hi Sara,



I checked the metadata folder on Github but didn’t see the chronometer file under Astronomy.  If you have it and can send it to me, I’ll update the file and upload it.



Teresa

**Comment by graytl** [comment]
oops, sorry, just saw the link in your original message….

**Comment by sterkenburgsara** [comment]
Yeah, I changed the XML filename to match the images, so now it's "20150417SG007-008.xml" - thanks!

**Comment by graytl** [comment]
Sara,



Do we need to change the Agent name to “Chronometerwerke GmbH” since this was the name of the company at the time it was made?  I believe “Werke” is just German for “works”.



Teresa

**Comment by sterkenburgsara** [comment]
Yes, please!
