### ISSUE TITLE
Add missing RefID (image filename) to image record

### ISSUE THREAD

**Issue by sterkenburgsara** [HeardLibrary/exhibitions#98]
The image record portion of the "Casseopeia" XML file is missing an image flename. [See here](https://github.com/HeardLibrary/exhibitions/blob/31997ea610467867caed5bb3f49e3f90e8099c86/Metadata/Visualizing-Data/Astronomy/Cassiopeia.xml#L71). 

I looked in your scanned images and couldn't find this image. Since this is a Hubble/ESA image (you put the URL in the file, so I was able to see what it looks like) - is it possible we didn't download this yet? Send the link to Henry in an email if not - and ask him to download/resize the image for FireSign requirements. Then put the filename he gives it in the `<refid>` space in the XML.

**Comment by graytl** [comment]
Hi Sara,



I’ve updated this file and renamed it opo0613c to match the filename on the original web site.  I also updated the creation date of the original image (2006-04-04 was the release date according to the download page), used this same date for the digital image (which may need to change to Henry’s image dates once he’s completed those), updated the url of the original image to the download page for the image, and corrected a couple of typos.  I can update Henry’s image dates once he’s completed those.



Let me know if anything else is missing on this file.



Teresa
